local testing_e2e = require("ascii-ui.testing.e2e")
local ui = require("ascii-ui")
local Select = ui.components.Select
local Paragraph = ui.components.Paragraph

describe("testing.e2e library", function()
	it("mount returns an E2EScreen", function()
		local App = ui.createComponent("Test", function()
			return Paragraph({ content = "hello" })
		end)
		local screen = testing_e2e.mount(App)
		assert(screen ~= nil)
		assert(screen._bufnr ~= nil)
	end)

	it("bufferContains checks nvim buffer content", function()
		local App = ui.createComponent("Test", function()
			return Paragraph({ content = "hello world" })
		end)
		local screen = testing_e2e.mount(App)
		assert(screen:bufferContains("hello"))
		assert(not (screen:bufferContains("missing")))
	end)

	it("waitForText waits for text to appear", function()
		local App = ui.createComponent("Test", function()
			return Paragraph({ content = "hello" })
		end)
		local screen = testing_e2e.mount(App)
		assert(screen:waitForText("hello"))
	end)

	it("hasText works on nvim buffer", function()
		local App = ui.createComponent("Test", function()
			return Select({ options = { "a", "b" } })
		end)
		local screen = testing_e2e.mount(App)
		assert(screen:hasText("[x] a"))
	end)

	it("press simulates keypress", function()
		local App = ui.createComponent("Test", function()
			return Select({ options = { "a", "b", "c" } })
		end)
		local screen = testing_e2e.mount(App)
		assert(screen:waitForText("[x] a"))

		screen:press("j")
		-- After pressing j, cursor should move to next focusable
		-- (This is a basic test - full cursor assertion would need cursorIsAt)
	end)

	it("toLines returns nvim buffer lines", function()
		local App = ui.createComponent("Test", function()
			return Select({ options = { "a", "b" } })
		end)
		local screen = testing_e2e.mount(App)
		screen:waitForText("[x] a")
		local lines = screen:toLines()
		-- Should contain the select options
		assert(#lines >= 2)
	end)
end)
