#!/bin/bash
# Run tests using mini.test (setup handled by scripts/minimal_init.lua)
# Adapted from https://github.com/rcasia/neotest-java/blob/main/scripts/test

NVIM=${NVIM:-nvim}
INIT=${INIT:-scripts/minimal_init.lua}

if [[ -n $1 ]] && [[ $1 == "--fail-fast" ]]; then
  echo "Running tests (fail-fast)"
  $NVIM --headless --noplugin -u "$INIT" \
    -c "lua MiniTest_run({ execute = { stop_on_error = true } })"
elif [[ -n $1 ]]; then
  echo "Running single test file: $1"
  $NVIM --headless --noplugin -u "$INIT" \
    -c "lua MiniTest_run({ collect = { find_files = function() return { '$1' } end } })"
else
  echo "Running all tests"
  $NVIM --headless --noplugin -u "$INIT" -c "lua MiniTest_run()"
fi
